import { redirect } from "next/navigation";
import { AppShell } from "@/shared/components/AppShell";
import { RolePreview } from "@/shared/components/RolePreview";
import { getCurrentUser, assertRoleAccess } from "@/core/auth/rbac";

export default async function VolunteerPage() {
  const user = await getCurrentUser();
  if (!assertRoleAccess(user, "/volunteer")) {
    redirect("/?denied=/volunteer");
  }

  return (
    <AppShell>
      <RolePreview
        title="Volunteer Deployment"
        description="Planned: incident-driven task assignment, shift heatmaps, and skill-matched dispatch generated by the Volunteer Agent. Not yet built in this scaffold."
        icon={
          <svg
            viewBox="0 0 24 24"
            width="30"
            height="30"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.6"
          >
            <path d="M12 3l2.5 5 5.5.7-4 3.9 1 5.4-5-2.7-5 2.7 1-5.4-4-3.9 5.5-.7z" />
          </svg>
        }
      />
    </AppShell>
  );
}
